statsearch = 0
clienttxt = 'C:/Program Files (x86)/Steam/steamapps/common/Path of Exile/logs/Client.txt'
soundfile = 'C:/Users/Shalw/github/PoeTools/Bell.wav'
tytrade = 'Ty and have a nice day Exile'
bgcolor = '#000000'
fgcolor = '#ff00ff'
textcolor = '#ff0000'
redeemer = 2
crusader = 3
warlord = 3
hunter = 1
