CURRENCY = {
    "Orb of Alteration": "alt",
    "Orb of Fusing": "fuse",
    "Orb of Alchemy": "alch",
    "Chaos Orb": "chaos",
    "Gemcutter's Prism": "gcp",
    "Exalted Orb": "exa",
    "Chromatic Orb": "chrom",
    "Jeweller's Orb": "jew",
    "Engineer's Orb": "engineers-orb",
    "Orb of Chance": "chance",
    "Cartographer's Chisel": "chisel",
    "Orb of Scouring": "scour",
    "Blessed Orb": "blessed",
    "Orb of Regret": "regret",
    "Regal Orb": "regal",
    "Divine Orb": "divine",
    "Vaal Orb": "vaal",
    "Orb of Annulment": "orb-of-annulment",
    "Orb of Binding": "orb-of-binding",
    "Ancient Orb": "anient-orb",
    "Orb of Horizons": "orb-of-horizons",
    "Harbinger's Orb": "harbingers-orb",
    "Scroll of Wisdom": "wis",
    "Portal Scroll": "port",
    "Armourer's Scrap": "scr",
    "Blacksmith's Whetstone": "whe",
    "Glassblower's Bauble": "ba",
    "Orb of Transmutation": "tra",
    "Orb of Augmentation": "aug",
    "Mirror of Kalandra": "mir",
    "Eternal Orb": "ete",
    "Perandus Coin": "p",
    "Silver Coin": "silver",
    "Annulment Shard": "annulment-shard",
    "Mirror Shard": "mirror-shard",
    "Exalted Shard": "exalted-shard",
    "Binding Shard": "binding-shard",
    "Horizon Shard": "horizon-shard",
    "Harbinger's Shard": "harbinger's-shard",
    "Engineer's Shard": "engineers-shard",
    "Ancient Shard": "ancient-shard",
    "Chaos Shard": "chaos-shard",
    "Regal Shard": "regal-shard",
    "Simple Sextant": "apprentice-sextant",
    "Prime Sextant": "journeyman-sextant",
    "Awakened Sextant": "master-sextant",
    "Blessing of Xoph": "blessing-xoph",
    "Blessing of Tul": "blessing-tul",
    "Blessing of Esh": "blessing-esh",
    "Blessing of Uul-Netol": "blessing-uul-netol",
    "Blessing of Chayula": "blessing-chayula",
    "Splinter of Xoph": "splinter-xoph",
    "Splinter of Tul": "splinter-tul",
    "Splinter of Esh": "splinter-esh",
    "Splinter of Uul-Netol": "splinter-uul",
    "Splinter of Chayula": "splinter-chayula",
    "Timeless Karui Splinter": "timeless-karui-splinter",
    "Timeless Maraketh Splinter": "timeless-maraketh-splinter",
    "Timeless Eternal Empire Splinter": "timeless-eternal-empire-splinter",
    "Timeless Templar Splinter": "timeless-templar-splinter",
    "Timeless Vaal Splinter": "timeless-vaal-splinter",
    "Stacked Deck": "stacked-deck",
    "Transumation Shard": "transmutation-shard",
    "Alteration Shard": "alteration-shard",
    "Alchemy Shard": "alchemy-shard",
    
    "Clear Oil": "clear-oil",
    "Sepia Oil": "sepia-oil",
    "Amber Oil": "amber-oil",
    "Verdant Oil": "verdant-oil",
    "Teal Oil": "teal-oil",
    "Azure Oil": "azure-oil",
    "Violet Oil": "violet-oil",
    "Crimson Oil": "crimson-oil",
    "Black Oil": "black-oil",
    "Opalescent Oil": "opalescent-oil",
    "Silver Oil": "silver-oil",
    "Golden Oil": "golden-oil",
    
    "Turbulent Catalyst": "turbulent-catalyst",
    "Imbued Catalyst": "imbued-catalyst",
    "Abrasive Catalyst": "abrasive-catalyst",
    "Tempering Catalyst": "tempering-catalyst",
    "Fertile Catalyst": "fertile-catalyst",
    "Prismatic Catalyst": "prismatic-catalyst",
    "Intrinsic Catalyst": "intrinsic-catalyst",
    
     "Sacrifice at Dusk": "dusk",
    "Sacrifice at Midnight": "mid",
    "Sacrifice at Dawn": "dawn",
    "Sacrifice at Noon": "noon",
    "Mortal Grief": "grie",
    "Mortal Rage": "rage",
    "Mortal Hope": "hope",
    "Mortal Ignorance": "ign",
    "Eber's Key": "eber",
    "Yriel's Key": "yriel",
    "Inya's Key": "inya",
    "Volkuur's Key": "volkuur",
    "Fragment of the Hydra": "hydra",
    "Fragment of the Phoenix": "phoenix",
    "Fragment of the Minotaur": "minot",
    "Fragment of the Chimera": "chimer",
    "Fragment of Enslavement": "fragment-of-enslavement",
    "Fragment of Eradication": "fragment-of-eradication",
    "Fragment of Constriction": "fragment-of-constriction",
    "Fragment of Purification": "fragment-of-purification",
    "Fragment of Terror": "fragment-of-terror",
    "Fragment of Emptiness": "fragment-of-emptiness",
    "Fragment of Shape": "fragment-of-shape",
    "Fragment of Knowledge": "fragment-of-knowledge",
    "Sacrifice Set": "sacrifice-set",
    "Mortal Set": "mortal-set",
    "Pale Court Set": "pale-court-set",
    "Key to the Crucible": "shaper-set",
    "Key to Decay": "key-to-decay",
    "Maddening Object": "maddening-object",
    "Xoph's Breachstone": "xophs-breachstone",
    "Tul's Breachstone": "tuls-breachstone",
    "Esh's Breachstone": "eshs-breachstone",
    "Uul-Netol's Breachstone": "uul-breachstone",
    "Chayula's Breachstone": "chayulas-breachstone",
    "Xoph's Charged Breachstone": "xophs-charged-breachstone",
    "Tul's Charged Breachstone": "tuls-charged-breachstone",
    "Esh's Charged Breachstone": "eshs-charged-breachstone",
    "Uul-Netol's Charged Breachstone": "uul-charged-breachstone",
    "Chayula's Charged Breachstone": "chayulas-charged-breachstone",
    "Xoph's Enriched Breachstone": "xoph-enriched-breachstone",
    "Tul's Enriched Breachstone": "tul-enriched-breachstone",
    "Esh's Enriched Breachstone": "esh-enriched-breachstone",
    "Uul-Netol's Enriched Breachstone": "uul-enriched-breachstone",
    "Chayula's Enriched Breachstone": "chayulas-enriched-breachstone",
    "Xoph's Pure Breachstone": "xophs-pure-breachstone",
    "Tul's Pure Breachstone": "tuls-pure-breachstone",
    "Esh's Pure Breachstone": "eshs-pure-breachstone",
    "Uul-Netol's Pure Breachstone": "uul-pure-breachstone",
    "Chayula's Pure Breachstone": "chayulas-pure-breachstone",
    "Timeless Karui Emblem": "timeless-karui-emblem",
    "Timeless Maraketh Emblem": "timeless-maraketh-emblem",
    "Timeless Eternal Emblem": "timeless-eternal-emblem",
    "Timeless Templar Emblem": "timeless-templar-emblem",
    "Timeless Vaal Emblem": "timeless-vaal-emblem",
    "Offering to the Goddess": "offer",
    "Ancient Reliquary Key": "ancient-reliquary-key",
    "Timeworn Reliquary Key": "timeworn-reliquary-key",
    "Divine Vessel": "divine-vessel",
    
    "Whispering Incubator": "whispering-incubator",
    "Fine Incubator": "fine-incubator",
    "Singular Incubator": "singular-incubator",
    "Cartographer's Incubator": "cartographer's-incubator",
    "Otherworldly Incubator": "otherworldly-incubator",
    "Abyssal Incubator": "abyssal-incubator",
    "Fragmented Incubator": "fragmented-incubator",
    "Skittering Incubator": "skittering-incubator",
    "Infused Incubator": "infused-incubator",
    "Fossilised Incubator": "fossilised-incubator",
    "Decadent Incubator": "decadent-incubator",
    "Diviner's Incubator": "diviner's-incubator",
    "Primal Incubator": "primal-incubator",
    "Enchanted Incubator": "enchanted-incubator",
    "Geomancer's Incubator": "geomancer's-incubator",
    "Ornate Incubator": "ornate-incubator",
    "Time-Lost Incubator": "time-lost-incubator",
    "Celestial Armoursmith's Incubator": "celestial-armoursmith's-incubator",
    "Celestial Blacksmith's Incubator": "celestial-blacksmith's-incubator",
    "Celestial Jeweller's Incubator": "celestial-jeweller's-incubator",
    "Eldritch Incubator": "eldritch-incubator",
    "Obscured Incubator": "obscured-incubator",
    "Foreboding Incubator": "foreboding-incubator",
    "Thaumaturge's Incubator": "thaumaturge's-incubator",
    "Mysterious Incubator": "mysterious-incubator",
    "Gemcutter's Incubator": "gemcutter's-incubator",
    "Feral Incubator": "feral-incubator",
    
     "Rusted Breach Scarab": "rusted-breach-scarab",
    "Polished Breach Scarab": "polished-breach-scarab",
    "Gilded Breach Scarab": "gilded-breach-scarab",
    "Rusted Cartography Scarab": "rusted-cartography-scarab",
    "Polished Cartography Scarab": "polished-cartography-scarab",
    "Gilded Cartography Scarab": "gilded-cartography-scarab",
    "Rusted Reliquary Scarab": "rusted-reliquary-scarab",
    "Polished Reliquary Scarab": "polished-reliquary-scarab",
    "Gilded Reliquary Scarab": "gilded-reliquary-scarab",
    "Rusted Bestiary Scarab": "rusted-bestiary-scarab",
    "Polished Bestiary Scarab": "polished-bestiary-scarab",
    "Gilded Bestiary Scarab": "gilded-bestiary-scarab",
    "Rusted Shaper Scarab": "rusted-shaper-scarab",
    "Polished Shaper Scarab": "polished-shaper-scarab",
    "Gilded Shaper Scarab": "gilded-shaper-scarab",
    "Rusted Elder Scarab": "rusted-elder-scarab",
    "Polished Elder Scarab": "polished-elder-scarab",
    "Gilded Elder Scarab": "gilded-elder-scarab",
    "Rusted Sulphite Scarab": "rusted-sulphite-scarab",
    "Polished Sulphite Scarab": "polished-sulphite-scarab",
    "Gilded Sulphite Scarab": "gilded-sulphite-scarab",
    "Rusted Divination Scarab": "rusted-divination-scarab",
    "Polished Divination Scarab": "polished-divination-scarab",
    "Gilded Divination Scarab": "gilded-divination-scarab",
    "Rusted Torment Scarab": "rusted-torment-scarab",
    "Polished Torment Scarab": "polished-torment-scarab",
    "Gilded Torment Scarab": "gilded-torment-scarab",
    "Rusted Ambush Scarab": "rusted-ambush-scarab",
    "Polished Ambush Scarab": "polished-ambush-scarab",
    "Gilded Ambush Scarab": "gilded-ambush-scarab",
    "Rusted Harbinger Scarab": "rusted-harbinger-scarab",
    "Polished Harbinger Scarab": "polished-harbinger-scarab",
    "Gilded Harbinger Scarab": "gilded-harbinger-scarab",
    "Rusted Perandus Scarab": "rusted-perandus-scarab",
    "Polished Perandus Scarab": "polished-perandus-scarab",
    "Gilded Perandus Scarab": "gilded-perandus-scarab",
    "Rusted Legion Scarab": "rusted-legion-scarab",
    "Polished Legion Scarab": "polished-legion-scarab",
    "Gilded Legion Scarab": "gilded-legion-scarab",
    
    "Primitive Alchemical Resonator": "primitive-alchemical-resonator",
    "Potent Alchemical Resonator": "potent-alchemical-resonator",
    "Powerful Alchemical Resonator": "powerful-alchemical-resonator",
    "Prime Alchemical Resonator": "prime-alchemical-resonator",
    "Primitive Chaotic Resonator": "primitive-chaotic-resonator",
    "Potent Chaotic Resonator": "potent-chaotic-resonator",
    "Powerful Chaotic Resonator": "powerful-chaotic-resonator",
    "Prime Chaotic Resonator": "prime-chaotic-resonator",
    
    "Scorched Fossil": "scorched-fossil",
    "Frigid Fossil": "frigid-fossil",
    "Metallic Fossil": "metallic-fossil",
    "Jagged Fossil": "jagged-fossil",
    "Aberrant Fossil": "aberrant-fossil",
    "Pristine Fossil": "pristine-fossil",
    "Dense Fossil": "dense-fossil",
    "Corroded Fossil": "corroded-fossil",
    "Prismatic Fossil": "prismatic-fossil",
    "Aetheric Fossil": "aetheric-fossil",
    "Serrated Fossil": "serrated-fossil",
    "Lucent Fossil": "lucent-fossil",
    "Shuddering Fossil": "shuddering-fossil",
    "Bound Fossil": "bound-fossil",
    "Perfect Fossil": "perfect-fossil",
    "Enchanted Fossil": "enchanted-fossil",
    "Encrusted Fossil": "encrusted-fossil",
    "Faceted Fossil": "faceted-fossil",
    "Bloodstained Fossil": "bloodstained-fossil",
    "Hollow Fossil": "hollow-fossil",
    "Fractured Fossil": "fractured-fossil",
    "Glyphic Fossil": "glyphic-fossil",
    "Tangled Fossil": "tangled-fossil",
    "Sanctified Fossil": "sanctified-fossil",
    "Gilded Fossil": "gilded-fossil",
    
    "Whispering Essence of Hatred": " whispering-essence-of-hatred",
    "Muttering Essence of Hatred": "muttering-essence-of-hatred",
    "Weeping Essence of Hatred": "weeping-essence-of-hatred",
    "Wailing Essence of Hatred": "wailing-essence-of-hatred",
    "Screaming Essence of Hatred": "screaming-essence-of-hatred",
    "Shrieking Essence of Hatred": "shrieking-essence-of-hatred",
    "Deafening Essence of Hatred": "deafening-essence-of-hatred",
    "Whispering Essence of Woe": "whispering-essence-of-woe",
    "Muttering Essence of Woe": "muttering-essence-of-woe",
    "Weeping Essence of Woe": "weeping-essence-of-woe",
    "Wailing Essence of Woe": "wailing-essence-of-woe",
    "Screaming Essence of Woe": "screaming-essence-of-woe",
    "Shrieking Essence of Woe": "shrieking-essence-of-woe",
    "Deafening Essence of Woe": "deafening-essence-of-woe",
    "Whispering Essence of Greed": "whispering-essence-of-greed",
    "Muttering Essence of Greed": "muttering-essence-of-greed",
    "Weeping Essence of Greed": "weeping-essence-of-greed",
    "Wailing Essence of Greed": "wailing-essence-of-greed",
    "Screaming Essence of Greed": "screaming-essence-of-greed",
    "Shrieking Essence of Greed": "shrieking-essence-of-greed",
    "Deafening Essence of Greed": "deafening-essence-of-greed",
    "Whispering Essence of Contempt": "whispering-essence-of-contempt",
    "Muttering Essence of Contempt": "muttering-essence-of-contempt",
    "Weeping Essence of Contempt": "weeping-essence-of-contempt",
    "Wailing Essence of Contempt": "wailing-essence-of-contempt",
    "Screaming Essence of Contempt": "screaming-essence-of-contempt",
    "Shrieking Essence of Contempt": "shrieking-essence-of-contempt",
    "Deafening Essence of Contempt": "deafening-essence-of-contempt",
    "Muttering Essence of Sorrow": "muttering-essence-of-sorrow",
    "Weeping Essence of Sorrow": "weeping-essence-of-sorrow",
    "Wailing Essence of Sorrow": "wailing-essence-of-sorrow",
    "Screaming Essence of Sorrow": "screaming-essence-of-sorrow",
    "Shrieking Essence of Sorrow": "shrieking-essence-of-sorrow",
    "Deafening Essence of Sorrow": "deafening-essence-of-sorrow",
    "Muttering Essence of Anger": "muttering-essence-of-anger",
    "Weeping Essence of Anger": "weeping-essence-of-anger",
    "Wailing Essence of Anger": "wailing-essence-of-anger",
    "Screaming Essence of Anger": "screaming-essence-of-anger",
    "Shrieking Essence of Anger": "shrieking-essence-of-anger",
    "Deafening Essence of Anger": "deafening-essence-of-anger",
    "Muttering Essence of Torment": "muttering-essence-of-torment",
    "Weeping Essence of Torment": "weeping-essence-of-torment",
    "Wailing Essence of Torment": "wailing-essence-of-torment",
    "Screaming Essence of Torment": "screaming-essence-of-torment",
    "Shrieking Essence of Torment": "shrieking-essence-of-torment",
    "Deafening Essence of Torment": "deafening-essence-of-torment",
    "Muttering Essence of Fear": "muttering-essence-of-fear",
    "Weeping Essence of Fear": "weeping-essence-of-fear",
    "Wailing Essence of Fear": "wailing-essence-of-fear",
    "Screaming Essence of Fear": "screaming-essence-of-fear",
    "Shrieking Essence of Fear": "shrieking-essence-of-fear",
    "Deafening Essence of Fear": "deafening-essence-of-fear",
    "Weeping Essence of Suffering": "weeping-essence-of-suffering",
    "Wailing Essence of Suffering": "wailing-essence-of-suffering",
    "Screaming Essence of Suffering": "screaming-essence-of-suffering",
    "Shrieking Essence of Suffering": "shrieking-essence-of-suffering",
    "Deafening Essence of Suffering": "deafening-essence-of-suffering",
    "Weeping Essence of Rage": "weeping-essence-of-rage",
    "Wailing Essence of Rage": "wailing-essence-of-rage",
    "Screaming Essence of Rage": "screaming-essence-of-rage",
    "Shrieking Essence of Rage": "shrieking-essence-of-rage",
    "Deafening Essence of Rage": "deafening-essence-of-rage",
    "Weeping Essence of Wrath": "weeping-essence-of-wrath",
    "Wailing Essence of Wrath": "wailing-essence-of-wrath",
    "Screaming Essence of Wrath": "screaming-essence-of-wrath",
    "Shrieking Essence of Wrath": "shrieking-essence-of-wrath",
    "Deafening Essence of Wrath": "deafening-essence-of-wrath",
    "Weeping Essence of Doubt": "weeping-essence-of-doubt",
    "Wailing Essence of Doubt": "wailing-essence-of-doubt",
    "Screaming Essence of Doubt": "screaming-essence-of-doubt",
    "Shrieking Essence of Doubt": "shrieking-essence-of-doubt",
    "Deafening Essence of Doubt": "deafening-essence-of-doubt",
    "Wailing Essence of Anguish": "wailing-essence-of-anguish",
    "Screaming Essence of Anguish": "screaming-essence-of-anguish",
    "Shrieking Essence of Anguish": "shrieking-essence-of-anguish",
    "Deafening Essence of Anguish": "deafening-essence-of-anguish",
    "Wailing Essence of Loathing": "wailing-essence-of-loathing",
    "Screaming Essence of Loathing": "screaming-essence-of-loathing",
    "Shrieking Essence of Loathing": "shrieking-essence-of-loathing",
    "Deafening Essence of Loathing": "deafening-essence-of-loathing",
    "Wailing Essence of Spite": "wailing-essence-of-spite",
    "Screaming Essence of Spite": "screaming-essence-of-spite",
    "Shrieking Essence of Spite": "shrieking-essence-of-spite",
    "Deafening Essence of Spite": "deafening-essence-of-spite",
    "Wailing Essence of Zeal": "wailing-essence-of-zeal",
    "Screaming Essence of Zeal": "screaming-essence-of-zeal",
    "Shrieking Essence of Zeal": "shrieking-essence-of-zeal",
    "Deafening Essence of Zeal": "deafening-essence-of-zeal",
    "Screaming Essence of Misery": "screaming-essence-of-misery",
    "Shrieking Essence of Misery": "shrieking-essence-of-misery",
    "Deafening Essence of Misery": "deafening-essence-of-misery",
    "Screaming Essence of Dread": "screaming-essence-of-dread",
    "Shrieking Essence of Dread": "shrieking-essence-of-dread",
    "Deafening Essence of Dread": "deafening-essence-of-dread",
    "Screaming Essence of Scorn": "screaming-essence-of-scorn",
    "Shrieking Essence of Scorn": "shrieking-essence-of-scorn",
    "Deafening Essence of Scorn": "deafening-essence-of-scorn",
    "Screaming Essence of Envy": "screaming-essence-of-envy",
    "Shrieking Essence of Envy": "shrieking-essence-of-envy",
    "Deafening Essence of Envy": "deafening-essence-of-envy",
    "Essence of Hysteria": "essence-of-hysteria",
    "Essence of Insanity": "essence-of-insanity",
    "Essence of Horror": "essence-of-horror",
    "Essence of Delirium": "essence-of-delirium",
    "Remnant of Corruption": "remnant-of-corruption",
}